version: '3.8'
services:
  mongo:
    image: mongo:5
    volumes:
      - mongo:/data/db
    ports:
      - '27017:27017'
    command: mongod --quiet --logpath /dev/null 
    restart: unless-stopped
  
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dokchat
    volumes:
      - pgdata:/var/lib/postgresql/data/
    ports:
      - '5432:5432'

  redis:
    image: redis:7
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis:/data
    restart: unless-stopped

  stocked-up:
    image: mrbartusek/stocked-up:latest
    depends_on:
      - mongo
      - redis
    environment:
      - MONGO_URL=mongodb://mongo/stockedUp
      - REDIS_HOST=redis
      - PORT=8081
    env_file: .stockedup.env
    ports:
      - 8081:8081
    restart: unless-stopped
  
  dokchat:
    image: mrbartusek/dokchat:latest
    depends_on:
      - postgres
      - redis
    environment:
      - DB_HOST=postgres
      - REDIS_HOST=redis
      - PORT=8080
    env_file: .dokchat.env
    ports:
      - 8080:8080
    restart: unless-stopped

volumes:
  mongo:
  redis:
  pgdata:
